" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" pathogen manages plugins
runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()
call pathogen#helptags()

" place backup files in folders dedicated to temporary files
set backupdir=~/.vim/tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set directory=~/.vim/tmp,~/.tmp,~/tmp,/var/tmp,/tmp

" syntax highlighting
syntax enable

" colorscheme
set background=dark
let g:solarized_termcolors=256
colorscheme solarized

" tabstop settings
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

" Autoindentation is useful, too
set autoindent

" Search is only case-sensitive for upper-case characters
set ignorecase
set smartcase
set hlsearch
set incsearch

set mouse=nvc " allow mouse in normal, visual, and command-line mode only (see help mouse)

" For vim-powerline theme
set laststatus=2
let g:airline_powerline_fonts = 1

" automatically reload files
set autoread

" Remember more commands and search history
set history=1000

" Make tab completion for files/buffers act like bash
set wildmenu
set wildignore=*.pyc,*.class

" Turn on line numbers
set number

" Open split panes below or to the right (see
" https://github.com/thoughtbot/dotfiles/)
set splitbelow
set splitright

" navigate splits
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" remap escape (eliminates reaching for escape key)
inoremap jj <ESC>

" Leader key on space bar
let mapleader = ' '

" show commands
set showcmd

" display at least three lines when scrolling
set scrolloff=3

" allow to save files with root permissions
cmap w!! w !sudo tee >/dev/null %

" flake8 integration for python
autocmd FileType python map <buffer> <leader>f :call Flake8()<CR>
autocmd BufNewFile,BufRead *.py compiler nose

" NERDTree toggling
nmap <silent> <leader>n :NERDTreeToggle<CR>

" Gundo toggling
nmap <silent> <leader>g :GundoToggle<CR>

" ZoomWin toggling
nnoremap <silent> <leader><leader> :ZoomWin<CR>

" Gitv should automatically decide where to place preview
let g:Gitv_OpenHorizontal = "auto"

" Taglist variables
" Display function name in status bar:
let g:ctags_statusline=1
" Automatically start script
let generate_tags=1
" Displays taglist results in a vertical window:
let Tlist_Use_Horiz_Window=0
" Shorter commands to toggle Taglist display
nnoremap TT :TlistToggle<CR>
" Various Taglist diplay config:
let Tlist_Compact_Format = 1
let Tlist_Exit_OnlyWindow = 1           " exit if taglist is last window open
let Tlist_Show_One_File = 1             " only show tags for current buffer
let Tlist_Enable_Fold_Column = 0        " no fold column (only showing one file)
let Tlist_GainFocus_On_ToggleOpen = 1   " automatically gain focus
let Tlist_File_Fold_Auto_Close = 1
let Tlist_Inc_Winwidth = 0

" LaTeX suite
" REQUIRED. This makes vim invoke Latex-Suite when you open a tex file.
filetype plugin indent on

" IMPORTANT: grep will sometimes skip displaying the file name if you
" search in a single file. This will confuse Latex-Suite. Set your grep
" program to always generate a file-name.
set grepprg=grep\ -nH\ $*

" OPTIONAL: Starting with Vim 7, the filetype of empty .tex files defaults to
" 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
" The following changes the default filetype back to 'tex':
let g:tex_flavor='latex'

" use bibtex8 to support biblatex
let g:Tex_BibtexFlavor = "bibtex8"

" Taglist / LaTeX
let tlist_bib_settings   = 'bib;a:BibTeX-Authors;e:BibTeX-Entries;t:BibTeX-Titles;s:BibTeX-Strings'
let tlist_make_settings  = 'make;m:makros;t:targets'
let tlist_tex_settings   = 'latex;s:Contents;g:Graphics;i:Listings;l:\label;r:\ref;p:\pageref;b:\bibitem'

" Syntastic settings
let g:syntastic_error_symbol='✗'
let g:syntastic_warning_symbol='⚠'

" quick editing of .vimrc (from sanitz)
nnoremap <silent> <leader>e :e! ~/.vimrc<cr>
nnoremap <silent> <leader>s :source ~/.vimrc<cr>
